### PR TITLE
Feat/total earned changes

### LINKED ISSUE #276: Implement Total Earned % change

### PR DESCRIPTION
**Pull request by librepgp**
Closes #276

To solve this issue I created a front-end solution using a dict that saves the last collectedFee using the date as the key.

Tasks
- [x] Prototype solution  
- [ ] Refactor and add appropriate typescript types

### CODE REVIEW

**Comment by librepgp** [comment]
I didn't find an API in the tdex-daemon that gave me the collectedFees per date.

That would be the cleanest solution I think. But I don't know how to code in Go nor if it really can be done since I don't know the architecture of the daemon.

I did notice the daemon "GetMarketCollectedFee" endpoint has the necessary timestamps though.
https://github.com/tdex-network/tdex-daemon/blob/b5e6c358b6a19419779e5741fb9ee92066cf1539/internal/core/application/operator_service.go#L787

**Comment by tiero** [comment]
> I didn't find an API in the tdex-daemon that gave me the collectedFees per date.
> 
> That would be the cleanest solution I think. But I don't know how to code in Go nor if it really can be done since I don't know the architecture of the daemon.
> 
> I did notice the daemon "GetMarketCollectedFee" endpoint has the necessary timestamps though.
> https://github.com/tdex-network/tdex-daemon/blob/b5e6c358b6a19419779e5741fb9ee92066cf1539/internal/core/application/operator_service.go#L787
> 

The idea is to pull them down, cache it and group fee data by  timestamp.


Btw You can open up an issue detailing it as feature request on daemon repo and see if makes sense to add dedicated API or a filter field

**Comment by librepgp** [comment]
Perfect, that was my solution. I asked in case a cache wasn't sufficient. 

It's basically a dictionary with the date as key and the collectedFees as value.
`collectedFeesPerDay[date] = collectedFee`

The code is just missing the typescript types now.

**Comment by librepgp** [comment]
Its ready.

**Comment by Janaka-Steph** [comment]
When I log the date keys I get 
```
todayKey 4/21/2022
yesterdayKey 4/19/2022
beforeYesterdayKey 4/17/2022
```

As I understand the total fees are set for the current day. But what happen if the app has not been opened the day before? 
yesterdayFees is empty ?

In storage, `0/0/0:0` default value is kept while it should not.
`\"operator\":\"{\\\"collectedFeesPerDay\\\":{\\\"0/0/0\\\":0,\\\"4/21/2022\\\":0}}\"`

You can get past total fees by using `GetMarketReport` with a `customPeriod` time range. Look at the fees table in Market Overview to see how it is used.

@tiero @librepgp

**Comment by librepgp** [comment]
Thanks for pointing out ``GetMarketReport`` that would work better indeed. I'll use that instead then.

The ``0/0/0`` key is just old browser cache. It was no longer being used on the last commit.

**Comment by Janaka-Steph** [comment]
> Thanks for pointing out `GetMarketReport` that would work better indeed. I'll use that instead then.

Sure

> The `0/0/0` key is just old browser cache. It was no longer being used on the last commit.

No I think it's the initial state being persisted

**Pull request closed without merging**
