### PR TITLE
Add user menu dropdown

### PR DESCRIPTION
**Pull request by Janaka-Steph**
Custom solution was chosen because of bugs in Antd Dropdown/Menu components.
Menu is revealed on hover above the three dots button and closed on click anywhere. 

Please review @tiero

### CODE REVIEW

**Comment by librepgp** [comment]
It works great.

I would just recommend to return the ``onClick={() => navigate(SETTINGS_ROUTE)}`` into the three-dots menu button so it isn't inert and clicking it results in an action. 

Like a little shortcut. That way we save the user the 'three-steps' of ``hovering``, then ``moving the mouse into "General Settings"`` and then ``clicking``.

**Comment by Janaka-Steph** [comment]
> It works great.
> 
> I would just recommend to return the `onClick={() => navigate(SETTINGS_ROUTE)}` into the three-dots menu button so it isn't inert and clicking it results in an action.
> 
> Like a little shortcut. That way we save the user the 'three-steps' of `hovering`, then `moving the mouse into "General Settings"` and then `clicking`.

You propose that click on three-dots btn direct user to settings page? I think it's confusing.

**Comment by librepgp** [comment]
Clicking the button and not doing any action is also confusing UX for a button. I don't feel strongly about it, up to you really.

Otherwise LGTM.

**Comment by Janaka-Steph** [comment]
> Clicking the button and not doing any action is also confusing UX for a button. I don't feel strongly about it, up to you really.
> 
> Otherwise LGTM.

It opens the dropdown. Since hover already opens it it seems doing nothing. I would rather remove the open on hover.

**Pull request merged**
