### PR TITLE
Add cors headers to http endpoint responses

### PR DESCRIPTION
**Pull request by altafan**
This adds cors headers to the response of proxy's HTTP endpoints /healthcheck and /connect.

Please @tiero @Janaka-Steph review this.

### CODE REVIEW

**Comment by Janaka-Steph** [comment]
@altafan @tiero can we restrain Acces control allow origin to localhost:3003 ?
How can I see proxy logs ? Can we log to a file ?

**Comment by tiero** [comment]
> @altafan @tiero can we restrain Acces control allow origin to localhost:3003 ? 

Good point.

> How can I see proxy logs ? Can we log to a file ?

Not sure where the standard output is redirected in a sidecar in Tauri.

But yes we can log to a file 

@altafan  with logrus

```
// You could set this to any `io.Writer` such as a file
  // file, err := os.OpenFile("logrus.log", os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0666)
  // if err == nil {
  //  log.Out = file
  // } else {
  //  log.Info("Failed to log to file, using default stderr")
  // }
```

**Comment by Janaka-Steph** [comment]
@altafan @tiero I tried `log.Out` but the method doesn't exist. Maybe we can use another logger, seems there are better libs.

**Comment by altafan** [comment]
> @altafan @tiero can we restrain Acces control allow origin to localhost:3003 ?

We cannot hardcode localhost:3003 if the user is able to change the running port (via PORT env var)

**Comment by altafan** [comment]
> How can I see proxy logs ? Can we log to a file ?

Done. The proxy now accepts an optional flag --log-to-file to redirects logs to `rpc_proxy.log`.

To test it out, you need to run `make build` before starting the tauri app in order to update the binary of the proxy.

You can then find the file at path `src-tauri/rpc_proxy.log` in dev mode.

**Comment by Janaka-Steph** [comment]
@altafan restraining to localhost without port ?

**Comment by altafan** [comment]
@Janaka-Steph Done.

**Pull request merged**
